version: '3.8'

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io  # 配置为代理 Docker Hub
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs

networks:
  default:
    external:
      name: zeabur-network
